@ color.S
#ifndef COLOR_S
#define COLOR_S

#define FG_BLACK()    30
#define FG_RED()      31
#define FG_GREEN()    32
#define FG_BROWN()    33
#define FG_BLUE()     34
#define FG_MAGENTA()  35
#define FG_CYAN()     36
#define FG_WHITE()    37
#define BG_BLACK()    40
#define BG_RED()      41
#define BG_GREEN()    42
#define BG_BROWN()    43
#define BG_BLUE()     44
#define BG_MAGENTA()  45
#define BG_CYAN()     46
#define BG_WHITE()    47
#define BG_DEFAULT()  49

#endif
